name: run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements-dev.txt'
    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with black
      run: black --check -v .
    - name: Run unit test
      run: pytest -m "not distributed" --cov-report xml --cov=exhaustive_weighted_random_sampler
    - name: Run distributed unit test
      run: pytest -n 2 -m distributed --dist each
    - name: Report coverage
      uses: codecov/codecov-action@v3.1.1
      with:
        files: coverage.xml
